# Generated by Django 4.0.4 on 2022-05-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InGoodHandsApp', '0003_alter_institution_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.CharField(choices=[('FA', 'fundacja'), ('OP', 'organizacja pozarządowa'), ('ZL', 'zbiórka lokalna')], default='FA', max_length=2),
        ),
    ]
